Repository YTiStrafeNubzHD/EssentialsPE, pull requests merged in 2018-08, with the labels that each got.

#7 Update UpdateFetchTask.php
  src/EssentialsPE/Tasks/Updater/UpdateFetchTask.php
Labels: Enhancement

#6 Update BaseAPI.php
  src/EssentialsPE/BaseFiles/BaseAPI.php
Labels: Enhancement, Unclear/Question

#9 Fixes GeoLocation
  src/EssentialsPE/Tasks/GeoLocation.php
Labels: Enhancement, Status: Work in progress
